#include <stdio.h>
  int main()
  {
  void	*new_pointer;
  int a;
  new_pointer = &a;
ft_printf("char : %c\n | string : %s\n | int : %d | unsigned :%u | pointer : %p", 'a', "hello", 10, 42516547, new_pointer);
  ft_printf("Print max int: %d\nPrint min int: %d\n", 2147483647, -2147483648);
  ft_printf("----------------\n");
  ft_printf("Print max int: %i\nPrint min int: %i\n", 2147483647, -2147483648);
  ft_printf("----------------\n");
  ft_printf("Print a string : %s\n", "Hello, comment ca va?\nCa va!");
  ft_printf("----------------\n");
  ft_printf("Print first ascii char : %c\nPrint last ascii char : %c\n", '!', '-');
  ft_printf("----------------\n");
  ft_printf("Printf hex integer : %x\n", 123);
  printf("Real printf : %x\n", 123);
  ft_printf("----------------\n");
  ft_printf("Print HEX integer : %X\n", 45);
  printf("Real printf : %X\n", 45);
  ft_printf("----------------\n");
  ft_printf("Print a pointer adress : %p\n", new_pointer);
  printf("Real printf : %p\n", new_pointer);
  ft_printf("----------------\n");
  ft_printf("Print max unsigned int : %u\n", 4294967295);
  printf("Real printf: %ld\n", 4294967295);
  ft_printf("----------------\n");
  ft_printf("%%hello\n");
  printf("%%hello\n");
  ft_printf("----------------\n");
  ft_printf("%%%%%\n", "hello");
  printf("%%%%%\n", "hello");
  ft_printf("----------------\n");
  ft_printf("%");
  printf("%");
  ft_printf("----------------\n");
  ft_printf("%%\n");
  printf("%%\n");
  ft_printf("----------------\n");
  ft_printf("%s%\n", "Hello");
  printf("%s%\n","Hello"); 
 ft_printf(" %d ", -1);
  ft_printf(" %d ", -1);
  ft_printf(" %d ", -9);
	ft_printf(" %d ", -10);
ft_printf(" %d ", -11);
ft_printf(" %d ", -14);
 ft_printf(" %d ", -15);
	ft_printf(" %d ", -16);
   ft_printf(" %d ", -99);
 ft_printf(" %d ", -100);
